### ISSUE TITLE
Don't append DeviceClass.name to Device.name

### ISSUE THREAD

**Issue by rhythm-section** [guh/guh#154]
Currently when a user adds a customized name to a device, this name (inside Device.params) is automatically added to Device.name. E.g when the user chooses "My Button" as name for a Device of DeviceClass "ON/OFF Button" the following changes are made:

Before:
Device.name = "ON/OFF Button"

After:
Device.name = "My Button (ON/OFF Button)"

To have more control over the interface it would be great when Device.name is only changed to "My Button". If DeviceClass.name ("ON/OFF Button") is needed, the interface can fetch it additionally.

**Comment by t-mon** [comment]
yes, good point, there is currently a little bit confusion in the plugins...

the device.name is meant to describe the name of the device class. The problem here is: the "device.name / device class name" is not changeable...and will not be stored...
The user defined name actually should be a param called "name". 

The example with the button (or openweathermap) was just a workaround...because the edit method was missing until yesterday. Focus on the parameter name, not the device.name.

currently, not every deviceclass has the param "name"...I will change that in each plugin as soon as possible. 
if you have a AutoDevice or a DiscoveredDevice, the param name will be initialized with a default name (or a name which makes sense depending on the deviceclass) and the user has to edit the name afterwards if needed...
