### ISSUE TITLE
Raspbian Jessie: guhd -h >ungültiger Maschinenbefehl

### ISSUE THREAD

**Issue by thymjan** [guh/guh#385]
Tried to install guh on a raspberry pi zero with jessie, but failed.
I followed the instructions described in the wiki:
"Install guh on Debian jessie (existing system)"

After installing, when I trie to start guhd or type "guhd -h" to get help the systems answers with "ungültiger Maschinenbefehl".

Can you give me a hint what went wrong?

**Comment by t-mon** [comment]
We stopped the support for the armv5 platforms since the maintenance process was to heavy (manual cross building of Qt libs). If you install the jessie builds (armhf) now, the package is really build for armv7, so I think that's the problem here. I have to update the wiki, sorry.
In the past the jessie armhf package was named armhf, but it was the build for the Raspberry Pi 1. There was/is a big problem with the naming (armhf vs. armel). We changed that and support from now on only real `armhf`, `i386` and `amd64` architectures.

**Comment by thymjan** [comment]
So the only raspberry supported is the Raspberry Pi 2?

______________________________
Stefan Johs. Theurer
sttheurer@googlemail.com

**Comment by t-mon** [comment]
Yes, or the Beaglebone Black, basically all armhf devices with Debian Jessi, or Ubuntu Vivid, Wily or Xenial systems. The problem with non armhf platforms is the cross compile process since there is no qmake which supports crosscompiling (except armhf, i386 and amd64). In the past I cross-compiled all libs by hand, that was to time consuming...
You can try to compile guh from source on the device, but that takes a really long time.

**Comment by thymjan** [comment]
With the image served for download for the Raspberry Pi 2 I've got success. guhd is running.
